# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18qP2uyKNr1Pd4zWcIYbxyfzynpkN5Gm8
"""

import streamlit as st

st.write("""
# Two Numbler Multiplication App

This app multiplies two number
""")

st.header('User Input Parameters')

n1 = st.number_input("Number_1")
n2 = st.number_input("Number_2")

if st.button('Calculate'):
    prod = n1 * n2
    st.write(prod)
